"""Add proper network trusted contacts support

Revision ID: 0a7024ec07dc
Revises: 3f0118bfe08e
Create Date: 2025-11-26 10:37:59.753721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a7024ec07dc'
down_revision = '3f0118bfe08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_network_recipient'))
        batch_op.drop_index(batch_op.f('idx_network_requester'))
        batch_op.drop_index(batch_op.f('idx_network_status'))
        batch_op.create_index(batch_op.f('ix_network_connections_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_connections_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_connections_status'), ['status'], unique=False)
        batch_op.drop_column('accepted_at')

    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_sos_status'))
        batch_op.drop_index(batch_op.f('idx_sos_user'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trusted_contacts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted_contacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))

    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sos_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sos_status'), ['status'], unique=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_network_connections_status'))
        batch_op.drop_index(batch_op.f('ix_network_connections_requester_id'))
        batch_op.drop_index(batch_op.f('ix_network_connections_recipient_id'))
        batch_op.create_index(batch_op.f('idx_network_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_network_requester'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_network_recipient'), ['recipient_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
