"""Add network connections clean

Revision ID: 3f0118bfe08e
Revises: b8ae916f008d
Create Date: 2025-11-25 22:00:37.909174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0118bfe08e'
down_revision = 'b8ae916f008d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               existing_nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               existing_nullable=True)

    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               existing_nullable=True)

    with op.batch_alter_table('star_ratings', schema=None) as batch_op:
        batch_op.alter_column('rated_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('star_ratings', schema=None) as batch_op:
        batch_op.alter_column('rated_at',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('last_updated',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
