"""Initial migration for all models

Revision ID: b8ae916f008d
Revises: 
Create Date: 2025-11-07 23:34:25.250195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8ae916f008d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_votes_username'))

    op.drop_table('app_votes')
    op.drop_table('notification_subscriptions')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('star_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_star_ratings_rated_at'), ['rated_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('star_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_star_ratings_rated_at'))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_timestamp'))

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_created_at'))

    op.create_table('notification_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('auth_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('p256dh_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_subscriptions_pkey')),
    sa.UniqueConstraint('endpoint', name=op.f('notification_subscriptions_endpoint_key'))
    )
    op.create_table('app_votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('voted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name=op.f('app_votes_username_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_votes_pkey'))
    )
    with op.batch_alter_table('app_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_votes_username'), ['username'], unique=False)

    # ### end Alembic commands ###
