"""Add accepted_at to network_connections

Revision ID: f0afff306f81
Revises: 0a7024ec07dc
Create Date: 2025-11-26 10:56:06.680932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0afff306f81'
down_revision = '0a7024ec07dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_network_connections_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_network_connections_requester_id'))
        batch_op.drop_index(batch_op.f('ix_network_connections_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_connections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_connections_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_connections_recipient_id'), ['recipient_id'], unique=False)
        batch_op.drop_column('accepted_at')

    # ### end Alembic commands ###
