"""Add resolved_at and resolved_by to sos_alerts

Revision ID: f566a8a93bea
Revises: f8554f5826ec
Create Date: 2025-11-26 21:03:02.601333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f566a8a93bea'
down_revision = 'f8554f5826ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('resolved_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    # ### end Alembic commands ###
