"""Add legacy_contacts to users

Revision ID: f8554f5826ec
Revises: f0afff306f81
Create Date: 2025-11-26 11:20:19.250813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8554f5826ec'
down_revision = 'f0afff306f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_contacts', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('legacy_contacts')

    # ### end Alembic commands ###
